### ISSUE TITLE
ocdev with Python 3.2 (Debian Wheezy)

### ISSUE THREAD

**Issue by bnoffer** [owncloud/ocdev#37] opened 2015-08-26 08:40 UTC
Just setup a dev. environment on a Debian Wheezy System which still uses Python 3.2.

In order to get ocdev to work you need to install legacy versions of Jinja2 and MarkupSafe. This is because the newer versions require Python 3.3.

So to get ocdev to work use:

pip install -Iv Jinja2==2.6
pip install -Iv MarkupSafe==0.15
pip install ocdev

I hope this helps others coming across this issue.

**Comment by BernhardPosselt** [comment] 2015-12-22 10:56
Closing this because:
* Debian Jessie should be popular enough
* Wheezy is oldstable and certain packages are not maintained anymore or removed which makes it hard to use on productive systems

Thanks for the info! I think people will be able to find it even when the issue is closed ;)

**Closed by BernhardPosselt** 2015-12-22 10:56 UTC
